`timescale 1ns / 1ps

module tb_img;
    
    parameter WIDTH = 8;
    parameter SIZE = 3;
    parameter PictureWidth  = 512;
    parameter PictureHeight = 512;
    
    logic clk;
    logic rst;
    logic enable;
    
    logic [WIDTH-1:0] pixel_in;
    logic [WIDTH-1:0] pixel_out;
    
    logic ready;
    
    logic [WIDTH-1:0] kernel [0:SIZE-1][0:SIZE-1];
    
    integer divisor = 1;
    
    integer fileIn;
    integer fileOut;
    
    integer width,height,maxval;
    string format;
    string comment;
    
    logic [WIDTH-1:0] image  [0:PictureHeight-1][0:PictureWidth-1];
    logic [WIDTH-1:0] result [0:PictureHeight-1][0:PictureWidth-1];
    
    integer r_out = 0;
    integer c_out = 0;
    
    conv2d_top #(
        .WIDTH(WIDTH),
        .SIZE(SIZE),
        .PictureWidth(PictureWidth)
    ) DUT (
        .clk(clk),
        .rst(rst),
        .enable(enable),
        .pixel_in(pixel_in),
        .kernel(kernel),
        .divisior(divisor),
        .ready(ready),
        .pixel_out(pixel_out)
    );
    
    always #5 clk = ~clk;
    
    initial begin
        kernel[2][0] = 1; kernel[2][1] = 2; kernel[2][2] = 1;
        kernel[1][0] = 2; kernel[1][1] = 4; kernel[1][2] = 2;
        kernel[0][0] = 1; kernel[0][1] = 2; kernel[0][2] = 1;
    
        divisor = 16;
    end
    
    always @(posedge clk) begin
        if(rst) begin
            c_out <= 0;
            r_out <= 0;
        end
        if(ready) begin
            result[r_out][c_out] <= pixel_out;
    
            if(c_out == PictureWidth-1) begin // после добавления расширения: c_out == PictureWidth-1. Без: c_out == PictureWidth-3
                c_out <= 0;
                r_out <= r_out + 1;
            end else begin
                c_out <= c_out + 1;
            end
        end
    end
    
    initial begin
        clk = 0;
        rst = 1;
        enable = 0;
    
        fileIn = $fopen("test.ppm","r");
        fileOut = $fopen("result.ppm","w");
    
        $fscanf(fileIn,"%s\n",format);
        $fgets(comment,fileIn);
        $fscanf(fileIn,"%d %d\n",width,height);
        $fscanf(fileIn,"%d\n",maxval);
    
        for(int r=0;r<PictureHeight;r++) begin
            for(int c=0;c<PictureWidth;c++) begin
                $fscanf(fileIn,"%d",image[r][c]);
            end
        end
    
        $fclose(fileIn);
    
        #20;
        rst = 0;
    
        #20;
        enable = 1;
    
        for(int r=0;r<PictureHeight;r++) begin
            for(int c=0;c<PictureWidth;c++) begin
                @(posedge clk);
                pixel_in <= image[r][c];
            end
        end
    
        @(posedge clk);
        pixel_in <= 'x;
        enable <= 0;
        wait(!ready)
        $fdisplay(fileOut,"P2");
        $fdisplay(fileOut,"# Generated by SystemVerilog");
        $fdisplay(fileOut,"%0d %0d",PictureWidth,PictureHeight); // после добавления расширения: PictureWidth, PictureHeight. Без: PictureWidth-2,PictureHeight-2
        $fdisplay(fileOut,"%0d",maxval);
     
        for(int r=0;r<PictureHeight;r++) begin        // после добавления расширения: PictureHeight. Без: PictureHeight-2
            for(int c=0;c<PictureWidth;c++) begin     // после добавления расширения: PictureWidth. Без: PictureWidth-2
                $fwrite(fileOut,"%0d ",result[r][c]);
            end
            $fwrite(fileOut,"\n");
        end
    
        $fclose(fileOut);
//        #20;
//        wait(!ready)
        $finish;
    end
    
endmodule