`timescale 1ns / 1ps

module tb_img;
    
    parameter WIDTH = 8;
    parameter SIZE = 5;
    parameter PictureWidth  = 512;
    parameter PictureHeight = 512;
    
    logic clk;
    logic rst;
    logic enable;
    
    logic [WIDTH-1:0] pixel_in;
    logic [WIDTH-1:0] pixel_out;
    
    logic ready;
    
    logic [WIDTH-1:0] kernel [0:SIZE-1][0:SIZE-1];
    
    integer divisior = 1;
    
    integer fileIn;
    integer fileOut;
    
    integer width,height,maxval;
    string format;
    string comment;
    
    logic [WIDTH-1:0] image  [0:PictureHeight-1][0:PictureWidth-1];
    logic [WIDTH-1:0] result [0:PictureHeight-1][0:PictureWidth-1];
    
    integer r_out = 0;
    integer c_out = 0;
    
    conv2d_top #(
        .WIDTH(WIDTH),
        .SIZE(SIZE),
        .PictureWidth(PictureWidth)
    ) DUT (
        .clk(clk),
        .rst(rst),
        .enable(enable),
        .pixel_in(pixel_in),
        .kernel(kernel),
        .divisior(divisior),
        .ready(ready),
        .pixel_out(pixel_out)
    );
    
    always #5 clk = ~clk;
    
    initial begin
//        kernel[2][0] = 0; kernel[2][1] = 1; kernel[2][2] = 0;
//        kernel[1][0] = 1; kernel[1][1] = -4; kernel[1][2] = 1;
//        kernel[0][0] = 0; kernel[0][1] = 1; kernel[0][2] = 0;
//        divisior = 1;
        
//        kernel[2][0] = 1; kernel[2][1] = 2; kernel[2][2] = 1;
//        kernel[1][0] = 2; kernel[1][1] = 4; kernel[1][2] = 2;
//        kernel[0][0] = 1; kernel[0][1] = 2; kernel[0][2] = 1;
//        divisior = 16;

//        kernel[4][0] = 6;  kernel[4][1] = 24; kernel[4][2] = 36; kernel[4][3] = 24; kernel[4][4] = 6;
//        kernel[3][0] = 4;  kernel[3][1] = 16; kernel[3][2] = 24; kernel[3][3] = 16; kernel[3][4] = 4;
//        kernel[2][0] = 1;  kernel[2][1] = 4;  kernel[2][2] = 6;  kernel[2][3] = 4;  kernel[2][4] = 1;
//        kernel[1][0] = 4;  kernel[1][1] = 16; kernel[1][2] = 24; kernel[1][3] = 16; kernel[1][4] = 4;
//        kernel[0][0] = 6;  kernel[0][1] = 24; kernel[0][2] = 36; kernel[0][3] = 24; kernel[0][4] = 6;
//        divisior = 256;

//        kernel[2][0] = -1; kernel[2][1] = -2; kernel[2][2] = -1;
//        kernel[1][0] = 0; kernel[1][1] = 0; kernel[1][2] = 0;
//        kernel[0][0] = 1; kernel[0][1] = 2; kernel[0][2] = 1;
//        divisior = 1;

//        for (int r = 0; r < SIZE; r++)
//            for (int c = 0; c < SIZE; c++)
//                kernel[r][c] <= -1;
//        kernel[(SIZE-1)/2][(SIZE-1)/2] <= 9;
//        divisior = 1;

        kernel[4][0] = 0;  kernel[4][1] = 0; kernel[4][2] = -1; kernel[4][3] = 0; kernel[4][4] = 0;
        kernel[3][0] = 0;  kernel[3][1] = -1; kernel[3][2] = -2; kernel[3][3] = -1; kernel[3][4] = 0;
        kernel[2][0] = -1;  kernel[2][1] = -2;  kernel[2][2] = 16;  kernel[2][3] = -2;  kernel[2][4] = -1;
        kernel[1][0] = 0;  kernel[1][1] = -1; kernel[1][2] = -2; kernel[1][3] = -1; kernel[1][4] = 0;
        kernel[0][0] = 0;  kernel[0][1] = 0; kernel[0][2] = -1; kernel[0][3] = 0; kernel[0][4] = 0;
        divisior = 1;
    end
    
    always @(posedge clk) begin
        if(!rst) begin
            c_out <= 0;
            r_out <= 0;
        end
        if(ready) begin
            result[r_out][c_out] <= pixel_out;
    
            if(c_out == PictureWidth-1) begin
                c_out <= 0;
                r_out <= r_out + 1;
            end else begin
                c_out <= c_out + 1;
            end
        end
    end
    
    initial begin
        clk = 0;
        rst = 1;#20;
        rst = 0;
        enable = 0;
    
        fileIn = $fopen("test.ppm","r");
        fileOut = $fopen("result.ppm","w");
    
        $fscanf(fileIn,"%s\n",format);
        $fgets(comment,fileIn);
        $fscanf(fileIn,"%d %d\n",width,height);
        $fscanf(fileIn,"%d\n",maxval);
    
        for(int r=0;r<PictureHeight;r++) begin
            for(int c=0;c<PictureWidth;c++) begin
                $fscanf(fileIn,"%d",image[r][c]);
            end
        end
    
        $fclose(fileIn);
    
        #20;
        rst = 1;
    
        #20;
        enable = 1;
    
        for(int r=0;r<PictureHeight;r++) begin
            for(int c=0;c<PictureWidth;c++) begin
                @(posedge clk);
                pixel_in <= image[r][c];
            end
        end
    
        @(posedge clk);
        pixel_in <= 'x;
        enable <= 0;
        wait(!ready)
        $fdisplay(fileOut,"P2");
        $fdisplay(fileOut,"# Generated by SystemVerilog");
        $fdisplay(fileOut,"%0d %0d",PictureWidth,PictureHeight);
        $fdisplay(fileOut,"%0d",maxval);
     
        for(int r=0;r<PictureHeight;r++) begin
            for(int c=0;c<PictureWidth;c++) begin
                $fwrite(fileOut,"%0d ",result[r][c]);
            end
            $fwrite(fileOut,"\n");
        end
    
        $fclose(fileOut);
//        #20;
//        wait(!ready)
        $finish;
    end
    
endmodule